apiVersion: v1
kind: ReplicationController
metadata:
  name: mylogin-rc
spec:
  replicas: 2
  selector:
     app: mylogin
     version: 2.0.1
  template:
    metadata:
       labels:
         app: mylogin
         version: 2.0.1
    spec:
       containers:
         - name: mylogin-container
           image: kushiruthu-myrpo:2
           ports:
           - containerPort: 8080
