apiVersion: v1
kind: ReplicationController
metadata:
   name: mynginx-rc
spec:
  replecas: 2
  selector:
      app: mynginx
  template:
    metadata:
       labels:
          app: mynginx
  spec:
       containers:
       - name: myngix-container
         image: nginx
         ports:
          - containerport: 80
