apiVersion: v1
kind: ReplicationController
metadata:
  name: mytomcat-rc
spec:
  replicas: 2
  selector:
    app: mytomcat
  template:
    metadata:
      name: mytomcat
      labels:
        app: mytomcat
    spec:
      containers:
        - name: tomcat-container
          image:   tomcat-image
          ports:
            - containerPort: 80
